apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - skein.yaml
patches:
  - path: workplace-patch.yaml
  - path: workplace-frontend-patch.yaml
configMapGenerator:
  - name: atlas-skein-content
    files:
      - ../content/playbooks/atlas_delivery.yaml
generatorOptions:
  disableNameSuffixHash: false
