apiVersion: apps/v1
kind: Deployment
metadata:
  name: skein
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skein
  template:
    metadata:
      labels:
        app: skein
    spec:
      containers:
        - name: skein
          image: skein:0.2.0
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: skein-data
