-- Deliberately does nothing. Kept because schema_version records it.
--
-- This migration used to rename roster rows holding a system-actor name. It
-- was wrong in the way every hand-rolled rename is wrong: it moved
-- users.name, tasks.assignee and api_keys.owner, and left the other 44
-- attribution columns pointing at the freed name. Its guard sat on the first
-- statement only, so when the target name was taken the roster row stayed put
-- while the API key moved -- handing a live credential to a different account.
--
-- Moving a person is one code path, services/users.py::rename_user, which
-- knows all 47 columns and the private notes DB that SQL cannot reach.
-- Whoever runs the server gets the row named at boot (see app/main.py) and
-- renames it there. The door already refuses the identity meanwhile, so
-- nothing writes under it while it waits.
SELECT 1 WHERE 0;
