"""Rotation handoff generator: deterministic assembly of everything the
incoming roster needs, written as a markdown artifact. LLM narrative polish
can be layered on later, same pattern as digest._narrate."""

from pathlib import Path

from .. import config, db
from ..agents.identity import refuse_when_consultative
from . import scope


def generate_handoff(
    engagement_id: int, *, actor: str = "system", viewer: scope.Viewer = scope.NOBODY
) -> dict:
    refuse_when_consultative("generate handoffs")
    # Filtered by the CALLER, not locked to the workspace tier. Locked, a crew
    # member saw their engagement in GET /api/engagements and got "not found"
    # asking for its handoff — a correct refusal with a misleading sentence.
    # The pack contents below take the same viewer, and the artifact row takes
    # the engagement's tier so list_artifacts does not hand the path to
    # somebody who could not have generated it.
    efrag, ep = scope.visible_filter(viewer, "engagements")
    eng = db.query_one(
        f"SELECT * FROM engagements WHERE id = ? AND {efrag}",  # noqa: S608 — scope.visible_filter emits only bound marks
        (engagement_id, *ep),
    )
    if not eng:
        raise scope.missing("engagements", engagement_id)
    name = eng["name"]
    # From here the body is built for the ARTIFACT, not for the caller. The
    # row inserted below carries the engagement's tier, so a workspace handoff
    # generated by a strong user was a workspace document containing her
    # private decisions and her other crews' rows — the questions and
    # decisions sections carry no engagement link, so they select across the
    # whole platform. scope.audience narrows the writer to the document.
    viewer = scope.audience(eng["visibility"], eng["crew_id"], viewer)
    mfrag, mp = scope.visible_filter(viewer, "milestones")
    tfrag, tp = scope.visible_filter(viewer, "tasks", "t")
    lfrag, lp = scope.visible_filter(viewer, "lessons")

    milestones = db.query(
        f"SELECT * FROM milestones WHERE engagement_id = ? AND {mfrag}"  # noqa: S608 — scope.visible_filter emits only bound marks
        " ORDER BY due_date IS NULL, due_date",
        (engagement_id, *mp),
    )
    tasks = db.query(
        f"SELECT t.* FROM tasks t WHERE {tfrag}"  # noqa: S608 — scope.visible_filter emits only bound marks
        " AND (t.engagement_id = ? OR t.milestone_id IN (SELECT id FROM milestones WHERE engagement_id = ?))"
        " AND t.status != 'done'",
        (*tp, engagement_id, engagement_id),
    )
    from .portfolio import _linked_blockers

    # this engagement's, not the whole platform's
    blockers = _linked_blockers(engagement_id, viewer)
    qfrag, qp = scope.visible_filter(viewer, "questions")
    questions = db.query(
        f"SELECT * FROM questions WHERE status = 'open' AND {qfrag}",  # noqa: S608 — scope.visible_filter emits only bound marks
        tuple(qp),
    )
    dfrag, dp = scope.visible_filter(viewer, "decisions")
    decisions = db.query(
        f"SELECT * FROM decisions WHERE {dfrag} ORDER BY id DESC LIMIT 20",  # noqa: S608 — scope.visible_filter emits only bound marks
        tuple(dp),
    )
    # _readable, like every other section here: this renders into the handoff
    # markdown AND an artifact on disk carrying the engagement's tier, and a
    # proposal's `summary` is built out of its target row's own text.
    from .review import _readable

    pending = _readable(db.query("SELECT * FROM pending_changes WHERE status = 'pending'"), viewer)
    lessons = db.query(
        f"SELECT * FROM lessons WHERE {lfrag}"  # noqa: S608 — scope.visible_filter emits only bound marks
        " AND (engagement_id = ? OR project_class = ?)",
        (*lp, engagement_id, eng["project_class"]),
    )

    lines = [
        f"# Handoff package — {name}",
        "",
        f"*Class: {eng['project_class']} · Lead: {eng['lead'] or 'unset'} ·"
        f" Status: {eng['status']} · Generated: {db.now()} by {actor}*",
        "",
        f"## Summary\n{eng['summary'] or '(none recorded)'}",
        "",
        "## Milestone status",
    ]
    for m in milestones:
        lines.append(
            f"- [{m['status']}] #{m['id']} {m['title']}"
            + (f" — due {m['due_date']}" if m["due_date"] else "")
        )
    lines += ["", "## Open tasks"]
    lines += [
        f"- [{t['status']}/{t['priority']}] #{t['id']} {t['title']}"
        f" (@{t['assignee'] or 'unassigned'})"
        for t in tasks
    ] or ["- none"]
    lines += ["", "## Unresolved blockers (this engagement)"]
    lines += [
        f"- [{b['status']}/{b['impact']}] #{b['id']} {b['title']}"
        f" (owner: {b['owner'] or 'unowned'})"
        for b in blockers
    ] or ["- none"]
    lines += ["", "## Unanswered questions (team-wide)"]
    lines += [
        f"- #{q['id']} {q['question']} (→ {q['assigned_to'] or 'unassigned'})" for q in questions
    ] or ["- none"]
    lines += ["", "## Recent decisions (with rationale)"]
    lines += [
        f"- **{d['title']}** — {d['decision']}"
        + (f" *(context: {d['context']})*" if d["context"] else "")
        for d in decisions
    ] or ["- none"]
    lines += ["", "## Pending reviews (team-wide)"]
    lines += [f"- #{p['id']} {p['summary']} (proposed by {p['proposed_by']})" for p in pending] or [
        "- none"
    ]
    lines += ["", "## Lessons relevant to this class"]
    lines += [
        f"- {les['lesson']}" + (f" → {les['recommendation']}" if les["recommendation"] else "")
        for les in lessons
    ] or ["- none"]

    markdown = "\n".join(lines)
    safe_name = name.replace("/", "_")
    if safe_name in (".", ".."):
        safe_name = f"engagement-{engagement_id}"
    artifacts_dir = Path(config.DATA_DIR) / "artifacts" / safe_name
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    path = artifacts_dir / f"{db.now()[:10]}-handoff.md"
    path.write_text(markdown)

    aid = db.execute(
        "INSERT INTO artifacts (engagement_id, kind, title, path, created_by, created_at,"
        " visibility, crew_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
        (
            engagement_id,
            "handoff",
            f"Handoff — {name}",
            str(path),
            actor,
            db.now(),
            eng["visibility"],
            eng["crew_id"],
        ),
    )
    db.log_activity(actor, "generate_handoff", f"engagement #{engagement_id} -> artifact #{aid}")
    return {"artifact_id": aid, "path": str(path), "markdown": markdown}


def list_artifacts(engagement_id: int = 0, viewer: scope.Viewer = scope.NOBODY) -> list[dict]:
    # a row here carries a PATH to a markdown file holding the engagement's
    # work — generate_handoff tags it with that engagement's tier
    frag, vp = scope.visible_filter(viewer, "artifacts")
    if engagement_id:
        return db.query(
            f"SELECT * FROM artifacts WHERE engagement_id = ? AND {frag} ORDER BY id DESC",  # noqa: S608 — scope.visible_filter emits only bound marks
            (engagement_id, *vp),
        )
    return db.query(
        f"SELECT * FROM artifacts WHERE {frag} ORDER BY id DESC LIMIT 50",  # noqa: S608 — scope.visible_filter emits only bound marks
        tuple(vp),
    )
