"""Rotation handoff generator: deterministic assembly of everything the
incoming roster needs, written as a markdown artifact. LLM narrative polish
can be layered on later, same pattern as digest._narrate."""

from pathlib import Path

from .. import config, db
from ..agents.identity import refuse_when_consultative
from . import scope, wording

# Newest first, so the cap drops the oldest report. Both branches carry it:
# docs/CORRECTIONS.md states the rule as "on every branch", and the Reports
# page reads the length to decide whether to call it a total.
LIST_LIMIT = 50
# A markdown report past this is our own generator's fault, not a caller's.
MAX_ARTIFACT_BYTES = 8 * 1024 * 1024


def generate_handoff(
    engagement_id: int, *, actor: str = "system", viewer: scope.Viewer = scope.NOBODY
) -> dict:
    refuse_when_consultative("generate handoffs")
    # Filtered by the CALLER, not locked to the workspace tier. Locked, a crew
    # member saw their engagement in GET /api/engagements and got "not found"
    # asking for its handoff — a correct refusal with a misleading sentence.
    # The pack contents below take the same viewer, and the artifact row takes
    # the engagement's tier so list_artifacts does not hand the path to
    # somebody who could not have generated it.
    efrag, ep = scope.visible_filter(viewer, "engagements")
    eng = db.query_one(
        f"SELECT * FROM engagements WHERE id = ? AND {efrag}",  # noqa: S608 — scope.visible_filter emits only bound marks
        (engagement_id, *ep),
    )
    if not eng:
        raise scope.missing("engagements", engagement_id)
    name = eng["name"]
    # From here the body is built for the ARTIFACT, not for the caller. The
    # row inserted below carries the engagement's tier, so a workspace handoff
    # generated by a strong user was a workspace document containing her
    # private decisions and her other crews' rows — the questions and
    # decisions sections carry no engagement link, so they select across the
    # whole platform. scope.audience narrows the writer to the document.
    viewer = scope.audience(eng["visibility"], eng["crew_id"], viewer)
    mfrag, mp = scope.visible_filter(viewer, "milestones")
    tfrag, tp = scope.visible_filter(viewer, "tasks", "t")
    lfrag, lp = scope.visible_filter(viewer, "lessons")

    milestones = db.query(
        f"SELECT * FROM milestones WHERE engagement_id = ? AND {mfrag}"  # noqa: S608 — scope.visible_filter emits only bound marks
        " ORDER BY due_date IS NULL, due_date",
        (engagement_id, *mp),
    )
    from .work import redact_task_relationships

    tasks = redact_task_relationships(
        db.query(
            f"SELECT t.* FROM tasks t WHERE {tfrag}"  # noqa: S608 — scope.visible_filter emits only bound marks
            " AND (t.engagement_id = ? OR t.milestone_id IN (SELECT id FROM milestones WHERE engagement_id = ?))"
            " AND t.status != 'done'",
            (*tp, engagement_id, engagement_id),
        ),
        viewer,
    )
    from .portfolio import _linked_blockers

    # this engagement's, not the whole platform's
    blockers = _linked_blockers(engagement_id, viewer)
    qfrag, qp = scope.visible_filter(viewer, "questions")
    questions = db.query(
        f"SELECT * FROM questions WHERE status = 'open' AND {qfrag}",  # noqa: S608 — scope.visible_filter emits only bound marks
        tuple(qp),
    )
    dfrag, dp = scope.visible_filter(viewer, "decisions")
    decisions = db.query(
        f"SELECT * FROM decisions WHERE {dfrag} ORDER BY id DESC LIMIT 20",  # noqa: S608 — scope.visible_filter emits only bound marks
        tuple(dp),
    )
    # _readable, like every other section here: this renders into the handoff
    # markdown AND an artifact on disk carrying the engagement's tier, and a
    # proposal's `summary` is built out of its target row's own text.
    from .review import _readable

    pending = _readable(db.query("SELECT * FROM pending_changes WHERE status = 'pending'"), viewer)
    lessons = db.query(
        f"SELECT * FROM lessons WHERE {lfrag}"  # noqa: S608 — scope.visible_filter emits only bound marks
        " AND (engagement_id = ? OR project_class = ?)",
        (*lp, engagement_id, eng["project_class"]),
    )

    lines = [
        f"# Handoff package — {name}",
        "",
        f"*Class: {wording.flatten(eng['project_class'])} · Lead: {eng['lead'] or 'unset'} ·"
        f" Status: {eng['status']} · Generated: {db.now()} by {actor}*",
        "",
        f"## Summary\n{eng['summary'] or '(none recorded)'}",
        "",
        "## Milestone status",
    ]
    for m in milestones:
        lines.append(
            f"- [{m['status']}] #{m['id']} {wording.flatten(m['title'])}"
            + (f" — due {m['due_date']}" if m["due_date"] else "")
        )
    lines += ["", "## Open tasks"]
    lines += [
        f"- [{t['status']}/{t['priority']}] #{t['id']} {wording.flatten(t['title'])}"
        f" (@{t['assignee'] or 'unassigned'})"
        for t in tasks
    ] or ["- none"]
    lines += ["", "## Unresolved blockers (this engagement)"]
    lines += [
        f"- [{b['status']}/{b['impact']}] #{b['id']} {wording.flatten(b['title'])}"
        f" (owner: {b['owner'] or 'unowned'})"
        for b in blockers
    ] or ["- none"]
    lines += ["", "## Unanswered questions (team-wide)"]
    lines += [
        f"- #{q['id']} {wording.flatten(q['question'])} (→ {q['assigned_to'] or 'unassigned'})"
        for q in questions
    ] or ["- none"]
    lines += ["", "## Recent decisions (with rationale)"]
    lines += [
        f"- **{wording.flatten(d['title'])}** — {wording.flatten(d['decision'])}"
        + (f" *(context: {d['context']})*" if d["context"] else "")
        for d in decisions
    ] or ["- none"]
    lines += ["", "## Pending reviews (team-wide)"]
    lines += [f"- #{p['id']} {p['summary']} (proposed by {p['proposed_by']})" for p in pending] or [
        "- none"
    ]
    lines += ["", "## Lessons relevant to this class"]
    lines += [
        f"- {wording.flatten(les['lesson'])}"
        + (f" → {wording.flatten(les['recommendation'])}" if les["recommendation"] else "")
        for les in lessons
    ] or ["- none"]

    markdown = "\n".join(lines)
    safe_name = name.replace("/", "_")
    if safe_name in (".", ".."):
        safe_name = f"engagement-{engagement_id}"
    artifacts_dir = Path(config.DATA_DIR) / "artifacts" / safe_name
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    # the engagement id is in the FILE name, not just the directory: two
    # distinct names can sanitize to one directory ("ops/reset" and "ops_reset"
    # both become "ops_reset"), and then the dated path collides. The upsert
    # below matches on path alone, so the second engagement would take over the
    # first one's artifact row — returning an id whose engagement, title and
    # TIER belong to the other engagement, while the body it just wrote was
    # narrowed for this one's audience.
    path = artifacts_dir / f"{db.today().isoformat()}-handoff-{engagement_id}.md"
    path.write_text(markdown, encoding="utf-8")

    # The FILE is named by date, so a second handoff the same day overwrites
    # it. The row must follow, or the list carries two identical links to one
    # file and opening the older one shows the newer body — which is the same
    # upsert `rituals._write_artifact` makes for the same reason.
    existing = db.query_one("SELECT id FROM artifacts WHERE path = ?", (str(path),))
    if existing:
        db.execute(
            "UPDATE artifacts SET created_by = ?, created_at = ? WHERE id = ?",
            (actor, db.now(), existing["id"]),
        )
        db.log_activity(actor, "generate_handoff", f"#{engagement_id} {name} (rewritten)")
        return {"artifact_id": int(existing["id"]), "path": str(path), "markdown": markdown}
    aid = db.execute(
        "INSERT INTO artifacts (engagement_id, kind, title, path, created_by, created_at,"
        " visibility, crew_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
        (
            engagement_id,
            "handoff",
            f"Handoff — {name}",
            str(path),
            actor,
            db.now(),
            eng["visibility"],
            eng["crew_id"],
        ),
    )
    db.log_activity(actor, "generate_handoff", f"engagement #{engagement_id} -> artifact #{aid}")
    return {"artifact_id": aid, "path": str(path), "markdown": markdown}


class ArtifactUnreadable(RuntimeError):
    """The row is there and the caller may read it, and the FILE is not.

    Its own class rather than a bare RuntimeError so app/main.py can answer
    JSON for exactly these four raises. A handler on RuntimeError itself
    would catch every one in the process — Starlette's, anyio's, the SDK's —
    and put its raw message in a response body, which is how an error stops
    being ours and starts echoing something a caller never should see.
    """


def read_artifact(artifact_id: int, viewer: scope.Viewer = scope.NOBODY) -> dict:
    """One artifact's body, for a reader who may see the row.

    Every generator here (handoff, the week rituals, the digest, the exec
    readout) has written a markdown file and a row pointing at it, and nothing
    could read one back: `list_artifacts` hands out a server-side PATH, which
    a browser cannot open. The files were reachable only by shelling into the
    container.
    """
    frag, vp = scope.visible_filter(viewer, "artifacts")
    marks = ", ".join("?" for _ in _NOT_A_REPORT)
    # the same exclusion list list_artifacts uses. Filtering only the LISTING
    # would leave the JSON plan served as `markdown` to anybody who guessed a
    # sequential id, which is the reader this reachability was built for
    row = db.query_one(
        f"SELECT * FROM artifacts WHERE id = ? AND kind NOT IN ({marks}) AND {frag}",  # noqa: S608 — scope.visible_filter emits only bound marks
        (artifact_id, *_NOT_A_REPORT, *vp),
    )
    if not row:
        raise scope.missing("artifacts", artifact_id)
    # `path` is a stored string, and this call turns one into a file read. Every
    # writer today is our own generator under DATA_DIR, so the containment check
    # is not about them — it is about the next writer, and about a restored or
    # hand-edited row. Without it, one crafted `path` reads any file the server
    # user can (SKEIN_MODEL_API_KEY in the environment file, the private notes
    # DB that services/private_notes.py keeps out of every other surface).
    root = (Path(config.DATA_DIR) / "artifacts").resolve()
    try:
        path = Path(row["path"]).resolve()
    except ValueError as e:
        # a NUL byte in the stored path — pathlib's own message would cross the
        # API boundary as our error text
        raise ArtifactUnreadable(
            f"artifact #{artifact_id} has an unreadable stored path."
            " Check the row against data/artifacts, then regenerate it."
        ) from e
    if not path.is_relative_to(root):
        raise scope.missing("artifacts", artifact_id)
    # Everything past the scope filter and the containment check is OUR state,
    # never something a caller sent — so it stays a 500 and shows up in the
    # error rate, which is the signal an operator needs here. A 404 would say
    # "no such artifact" about a row the reader can plainly see listed.
    # is_file() is False for a FIFO and for a device node as well as for an
    # absent path, and that is the half that matters: read_text() on a FIFO
    # under data/artifacts blocks this worker thread for good.
    if not path.is_file():
        # a restored database beside an empty data volume: retention never
        # prunes artifacts, so the row outliving its file means the volume did
        raise ArtifactUnreadable(
            f"artifact #{artifact_id} has no file on disk."
            " Check that the volume holding data/artifacts is mounted."
        )
    # A generator writes a markdown report. Anything past this arrived by the
    # same route the containment check is written against, and read_text pulls
    # the whole file into the worker before FastAPI serializes it again.
    if path.stat().st_size > MAX_ARTIFACT_BYTES:
        raise ArtifactUnreadable(
            f"artifact #{artifact_id} is too large to read. Open the file on the server instead."
        )
    try:
        return {**row, "markdown": path.read_text(encoding="utf-8")}
    except (OSError, UnicodeDecodeError) as e:
        # a generator writes UTF-8 markdown; anything else under data/artifacts
        # arrived by the same route the containment check is written against
        raise ArtifactUnreadable(
            f"artifact #{artifact_id} is not readable text."
            " Check that the file is the markdown the generator wrote."
        ) from e


# Machinery, not a report. `plan-snapshot` (services/playbooks.py) is a JSON
# plan that only close_out_diff reads; Work → Reports renders every row it
# gets through a MARKDOWN reader, so leaving it in put a raw JSON blob at the
# top of a page whose subtitle promises digests and briefs — and it would eat
# the LIST_LIMIT budget the card's count reasons about.
_NOT_A_REPORT = ("plan-snapshot",)


def list_artifacts(engagement_id: int = 0, viewer: scope.Viewer = scope.NOBODY) -> list[dict]:
    # a row here carries a PATH to a markdown file holding the engagement's
    # work — generate_handoff tags it with that engagement's tier
    frag, vp = scope.visible_filter(viewer, "artifacts")
    marks = ", ".join("?" for _ in _NOT_A_REPORT)
    if engagement_id:
        return db.query(
            f"SELECT * FROM artifacts WHERE engagement_id = ? AND kind NOT IN ({marks})"  # noqa: S608 — scope.visible_filter emits only bound marks
            f" AND {frag} ORDER BY id DESC LIMIT ?",
            (engagement_id, *_NOT_A_REPORT, *vp, LIST_LIMIT),
        )
    return db.query(
        f"SELECT * FROM artifacts WHERE kind NOT IN ({marks}) AND {frag}"  # noqa: S608 — scope.visible_filter emits only bound marks
        " ORDER BY id DESC LIMIT ?",
        (*_NOT_A_REPORT, *vp, LIST_LIMIT),
    )
